<a href="https://colab.research.google.com/github/phaniranjan/tensorflow/blob/master/MyTensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%tensorflow_version 2.x
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.6/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [0]:
string = tf.Variable("This is string",tf.string)
number = tf.Variable(124,tf.int32)
floating = tf.Variable(12.312,tf.float16)

In [11]:
rank1_tensor = tf.Variable([12,34, 56], tf.int16)
rank2_tensor = tf.Variable([[123,24],[124,32]],tf.int32)
tf.rank(rank1_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [14]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [13]:
tf.shape(rank1_tensor)

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([3], dtype=int32)>

In [12]:
tf.shape(rank2_tensor)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 2], dtype=int32)>